In [1]:
import numpy as np

# Definimos la matriz X
X = np.array([[1, 0, 0, 0],
              [1, 1, 0, 0],
              [1, 1, 1, 0],
              [1, 1, 1, 1]])

# Imprimimos la matriz X
print("Matriz X:")
print(X)

# Calculamos la media de X y centramos los datos
X_media = X - np.mean(X, axis=0)

# Calculamos la matriz de covarianza de X
S = np.cov(X_media, rowvar=False)
print("\nMatriz de covarianza de X:")
print(S)

# Calculamos los eigenvalores y eigenvectores de la matriz de covarianza de X
eigen_val, eigen_vec = np.linalg.eigh(S)
print("\nEigenvalores de X:")
print(eigen_val)

# Definimos la matriz A
A = np.array([[3, 2, 1],
              [2, 4, 2],
              [1, 2, 3]])

# Imprimimos la matriz A
print("\nMatriz A:")
print(A)

# Calculamos la media de A y centramos los datos
A_media = A - np.mean(A, axis=0)

# Calculamos la matriz de covarianza de A
SA = np.cov(A_media, rowvar=False)
print("\nMatriz de covarianza de A:")
print(SA)

# Calculamos los eigenvalores y eigenvectores de la matriz de covarianza de A
eigen_val, eigen_vec = np.linalg.eigh(SA)
print("\nEigenvalores de A:")
print(eigen_val)


Matriz X:
[[1 0 0 0]
 [1 1 0 0]
 [1 1 1 0]
 [1 1 1 1]]

Matriz de covarianza de X:
[[0.         0.         0.         0.        ]
 [0.         0.25       0.16666667 0.08333333]
 [0.         0.16666667 0.33333333 0.16666667]
 [0.         0.08333333 0.16666667 0.25      ]]

Eigenvalores de X:
[0.         0.09763107 0.16666667 0.56903559]

Matriz A:
[[3 2 1]
 [2 4 2]
 [1 2 3]]

Matriz de covarianza de A:
[[ 1.          0.         -1.        ]
 [ 0.          1.33333333  0.        ]
 [-1.          0.          1.        ]]

Eigenvalores de A:
[0.         1.33333333 2.        ]
